# Site
title: Joe Nissen | Computer Science
description: >-
  CS master's student at Binghamton University focused on AI, machine learning, and quantum computing.
url: "https://joenissen.github.io"
baseurl: ""

# Author
author:
  name: Joe Nissen
  email: jnissen@binghamton.edu

# Files to exclude
exclude:
  - README.md
